### ISSUE TITLE
Contract <-> Model 간 의존 방향성 문제 

### ISSUE THREAD

**Issue by jaceshim** [gyuwon/ArchitecturalRunwayGuidelines#2]
Bounded Context 구성 설명에 나와 있는 아래 그림에서 
<img width="734" alt="contract" src="https://github.com/user-attachments/assets/40ffc38e-dfd9-4d0c-82b8-cbb5de88c7a4">

Contract이 B.C를 외부에 노출하는 인터페이스 개념이고 
외부에서 Contract 을 호출하는 경우 Contract이 Model을 호출 할것 같은데요~
이러면 화살표 방향이 반대가 되는게 맞는것 같아서 이슈 남겨 봅니다

**Comment by gyuwon** [comment]
의견 고맙습니다. :)

Contracts 모듈은 클라이언트가 인터페이스의 기능을 호출하기 위한 코드를 담습니다. 주로 메시지나 뷰모델 등의 스키마가 레코드 형태로 제공되고 일반적으로 논리(메서드)는 포함되지 않습니다.

예를 들어 BC1이 HTTP API를 제공하고 BC2가 이 API를 사용하는데(`BC1 <-- BC2`) BC1이 Contracts 모듈을 제공하지 않는다면 BC2는 BC1의 API 스키마에 맞게 메시지(입력 데이터)나 뷰모델(출력 데이터)을 표현하는 코드를 별도로 만들어야 합니다. 이 때 코드 중복과 스키마 불일치의 가능성이 발생합니다. 이런 불편함을 해결하기 위해 Contracts 모듈이 분리되고 BC1 외부로 공개됩니다.

여기서 만약 Contracts가 Model을 참조하고 또 기능을 호출한다면 BC1의 비즈니스 논리가 BC2에 노출됩니다. 이것은 우리가 원하는 설계가 아닙니다. BC1은 비즈니스 논리를 내부에 숨기고 인터페이스를 정의하는 영역만 클라이언트(BC2)에 공개하고 싶습니다.

반면에 Model은 인터페이스가 정의하는 기능을 구현하기 때문에 Contracts 모듈의 코드(명령 메시지나 뷰모델 레코드 형식 등)를 사용합니다.

이런 이유로 `Contracts uses Model`이 아니라 `Model uses Contracts`로 설계되었습니다.

**Comment by jaceshim** [comment]
제가 뭔가 구조를 잘못 이해하고 있는듯 하네요~
다시 한번 곱씹어 읽어 봐야 겠습니다.
답변 감사합니다 👍

**Comment by jaceshim** [comment]
제가 뭔가 구조를 잘못 이해하고 있는듯 하네요~
다시 한번 곱씹어 읽어 봐야 겠습니다.
답변 감사합니다 👍

**Comment by jaceshim** [comment]
다시 살펴 보니 
`외부에 노출하는 인터페이스 계약에 사용되는 메시지와 데이터를 정의한다`
이걸 제가 잘못 읽었었네요...
Contract이 외부에서 호출하는 메서드를 포함하고 있다고 착각했습니다 :(
